### ISSUE TITLE
MealApp Project : set up your Kanban board

### ISSUE THREAD

**Issue by Abenezer-Tilahun** [Abenezer-Tilahun/MealApp#21]
https://github.com/Abenezer-Tilahun/MealApp/projects/1

Our Team have two members 

- Student A( @Abenezer-Tilahun )
- Student B( @keza681 )

**Comment by elyor-doniyorov** [comment]
Hi @Abenezer-Tilahun and @keza681, 

In my opinion, your Kanban Board is ready!  There is nothing else to say other than... it's time to start working on the tasks :shipit: 


Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
